# Pipeline de integração contínua com Github
name: End-to-end tests 🧪 # criado 
on: [push] #qualquer push ou qualquer bransh vai desparar ele
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress 
        uses: cypress-io/github-action@v2